language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: amSnMAFUak63saqycstw+CVE9+UxFFMAUGdLSmNYlbCAZKb52SjPnk3t2othRXZIINBgE5grK93NF6Q0OR7F4n029RFDG3COCf7F+C4wh8HQEooCVrLXJitG3jGCmXZ4as5ft04tdqJsKVYVFU4fz4Pv1kEdhleBHiGY0g217Z5oA2/rsouWprN0maDm+OXh1E4gjYita3lqI+fbiHNOrIplaQqNsEByEbQh52ahuubZL3Ly4OzmdECLT7Ard/Xs2TTyy6zglZ4rQAJl9WyLT8gB01do80K8va0p7INng1dRuGxJvS76RjqLRNhcHLGYJmuOOoiEXv80AqjkIfPogM+5y1kiEKYfuthGTdE4Cwac7HxcvVI8vsYtiJWPvgt30MCGUSdhuUEMEHrDtqls52QSjsD3n+CkYAywXdjqeHKmbkROmooc1N22GAJST+LJXDCmzw2/7QGhuc65FbBfXxrI/MRFEmwalzoqYUcEG4hiJDbLD0rRHpT52HjqBBYsu+DPJBSDrn1jxPz4WYxjS4ptQhJvD8D2s0zTJCHxXxb0jN0VtdMQmw2tt68PB7o3kYPEsDfgHo9pKcjfrNRM8eK93bn5uV15goNuHY6vXEuYTnjjsTHAMlI/0NQ5UK67ddBvFJk3ZhCf28wk/GUZhO16pfCVEGCM7L+SELq9KU8=
